#!/bin/bash

# Quick commands for AWS deployment

echo "🐉 APEX DEPLOYMENT COMMANDS"
echo "============================"
echo ""
echo "After uploading aws-deploy/ folder, run these commands:"
echo ""
echo "# Navigate to deployment"
echo "cd ~/aws-deploy"
echo ""
echo "# Make scripts executable"
echo "chmod +x deploy.sh check_deployment.sh"
echo ""
echo "# Deploy everything (auto-installs, configures, starts services)"
echo "./deploy.sh"
echo ""
echo "# After deployment, check status"
echo "sudo supervisorctl status"
echo ""
echo "# Watch trading live"
echo "tail -f ~/apex/logs/trading-dragon.out.log"
echo ""
echo "# View all logs"
echo "tail -f ~/apex/logs/*.log"
echo ""
echo "# Restart services"
echo "sudo supervisorctl restart apex-full-stack:*"
echo ""
echo "# Stop services"
echo "sudo supervisorctl stop apex-full-stack:*"
echo ""
echo "# Start services"
echo "sudo supervisorctl start apex-full-stack:*"
echo ""
